### ISSUE TITLE
failure to get schema causes program crash

### ISSUE THREAD

**Issue by tomeichlersmith** [slaclab/slic#100]
I've been running a lot of HPS batch simulation recently and O(1%) of my jobs need to be resubmitted because they fail to get the GDML/LCDD schema from the lcsim website. This isn't horrible because resubmitting isn't the end of the world, but it is annoying and I feel like there is a way to get around this.

At least in my experience, you can disable "validation" of the GDML and so it doesn't need access to the schema anymore. This is helpful for cases where users aren't editing the detector geometry and just want to run many jobs over an already-validated geometry. I'm wondering if there is a similar thing we can do with the LCDD.

```
fatal error:  systemId:  line: 0 column: 0
unable to connect socket for URL 'http://www.lcsim.org/schemas/gdml/1.0/gdml_parameterised.xsd'
fatal error:  systemId: http://www.lcsim.org/schemas/gdml/1.0/gdml.xsd line: 8 column: 56
fatal error during schema scan

-------- EEEE ------- G4Exception-START -------- EEEE -------
*** G4Exception :
      issued by :
Failed to get the world volume.
*** Fatal Exception *** core dump ***
 **** Track information is not available at this moment
 **** Step information is not available at this moment

-------- EEEE -------- G4Exception-END --------- EEEE -------
```

**Comment by tomeichlersmith** [comment]
Nevermind, found that the issue is coming from the schema-specification in the LCDD (e.g. https://github.com/JeffersonLab/hps-java/blob/master/detector-data/detectors/HPS-PhysicsRun2016-Pass2/HPS-PhysicsRun2016-Pass2.lcdd) and so I can edit the top of the LCDDs to point to pre-downloaded schemas.

**Comment by normangraf** [comment]
Hi Tom,

You should never edit the lcdd files. Here are instructions on how to perform the schema validation locally:

https://confluence.slac.stanford.edu/display/ilc/ILC+Detector+Simulation+FAQ#:~:text=How%20can%20I%20make%20SLIC%20look%20for%20XML%20schemas%20in%20a%20local%20directory%3F

Norman

________________________________
