### ISSUE TITLE
Infinite loop in MCParticleManager when processing LCIO for event generation

### ISSUE THREAD

**Issue by chekanov** [slaclab/slic#11]
Hi, Jeremy

 I'm using SLIC 5.0.0 which has a simpler way to attribute secondary particles in MCParticleManager.cc . If this version is the same as 5.0.1, then there is an infinite loop for complex  Pythia8 events.

You can check it as this:
wget http://mc.hep.anl.gov/asc/hepsim/events/pp/100tev/qcd_pythia8_ptall/tev100_pythia8_jets_pt100_001.promc

and convert it to LCIO:
https://github.com/Argonne-National-Laboratory/ProMC/tree/master/examples/promc2lcio

then feed it to this version of SLIC. You will see that even 1st event never finishes due to recent changes in MCParticleManager.cc (?).

Wnen I use SLIC 5.0.0, I do not see problems.

This can be due to the way Pythia8 organizes events, I'm still not sure.
Interestingly enough, when I use Pythia6 record and simple events, I do not see problems

I'll test this more carefully when I make a full sim-reco chain using your github code without ilcsoft

best, Sergei

**Comment by JeremyMcCormick** [comment]
I think the issue probably has to do with the StdHep reader class from LCIO, which does most of the work of translating the event generator particles.  It may be that the HEPEVT records  have parent/daughter pointers between particles that causes an infinite loop.

This could be tested by using `LCStdHepRdr` instead of `LCStdHepRdrNew` in `MCParticleManager`.  The `New` class attempts to use both parent and daughter pointers but the other uses only one set of these pointers, which means some StdHep files are not processed correctly, but it could fix this particular issue.

**Comment by JeremyMcCormick** [comment]
Hi, Sergei.

Can you apply your patches which fix this on a proper fork of the current slic master from github?

Then it will be much easier for me to tell what you changed by just doing a PR on your fork.

Thanks.

**Comment by chekanov** [comment]
Hi, Jeremy

  sure, I'll folk it to the  current version I'm using in HepSim

best, Sergei

       Sergei Chekanov           | http://www.hep.anl.gov/chekanov/
       ===============           | Email: chekanov@anl.gov
      HEP Division, ANL          | Tel  : +01-630-252 6541
9700 S.Cass,Lemont, IL60439,USA | Fax  : +01-630-252-5782

**Comment by JeremyMcCormick** [comment]
Question: Did you just revert to using the `LCStdHepRdr` instead of `LCStdHepRdrNew` or were there additional changes?

**Comment by chekanov** [comment]
Hi, Jeremy

nope, did not do anything for LCStdHepRdr.

I hesitate a bit to put  Whit's slic code on public github under branch. 
I would need to ask Whit first, since this was his product

best, Sergei

       Sergei Chekanov           | http://www.hep.anl.gov/chekanov/
       ===============           | Email: chekanov@anl.gov
      HEP Division, ANL          | Tel  : +01-630-252 6541
9700 S.Cass,Lemont, IL60439,USA | Fax  : +01-630-252-5782

**Comment by JeremyMcCormick** [comment]
patches from Whit

[patch_first_commit.txt](https://github.com/slaclab/slic/files/945546/patch_first_commit.txt)

[patch_whit.txt](https://github.com/slaclab/slic/files/945547/patch_whit.txt)

**Comment by JeremyMcCormick** [comment]
From Sergei about converting from promc to LCIO MCParticle input:

it is inside the ProMC package:

https://atlaswww.hep.anl.gov/asc/promc/download/ProMC-1.6.tgz

unzip and look inside "examples/promc2lcio". It uses Java, so no  need to compile the entire package (which is in C++). There is README which shows how it works.

I use LCIO with "MCParticle", I do not use stdhep files for SLIC.
