### ISSUE TITLE
LCDD

### ISSUE THREAD

**Issue by whit2333** [slaclab/slic#24]
What is up with LCDD?

I don't know the history but it seems to have be annexed as part of [DD4hep](https://github.com/AIDASoft/DD4hep/blob/master/DDCore/include/DD4hep/LCDD.h). Is there a reason that a [separate library](https://github.com/slaclab/lcdd) exists for slic?

Not a real issue, but I was just curious. Feel free to close this right away.

**Comment by JeremyMcCormick** [comment]
LCDD is the geometry format for slic input files supported by a separate lcdd github project.

No, its not part of DD4hep.  There was a incomplete binding to DD4hep that I removed.
