### ISSUE TITLE
some problems with running slic

### ISSUE THREAD

**Issue by chekanov** [slaclab/slic#25]
Hello, Jeremy

 I've just tried the master after pull23:

 1) It still fails  with the error:  

....
Set Lorentz transformation angle to 7 mrad
G4VUserPhysicsList::PreparePhysicsTable  : No Process Manager for B*^+
B*^+ should be created in your PhysicsList

-------- EEEE ------- G4Exception-START -------- EEEE -------
*** G4Exception : Run0273
      issued by : G4VUserPhysicsList::PreparePhysicsTable
No process manager
*** Fatal Exception *** core dump ***
-------- EEEE -------- G4Exception-END --------- EEEE -------

*** G4Exception: Aborting execution ***
./A_RUN: line 142: 3468193 Aborted                 ${SLIC_DIR}/slic/bin/slic -P ${SLIC_DIR}/data/particle.tbl -x -i ${FTRUTH} -g ./${GEOM}/${GEOM}.lcdd -r $Nevents -m ./${GEOM}/config/defaultILCCrossingAngle.mac -o ${OUTF}.slcio

I'm using LCIO file with single pions (I've sent it to you by email). I also use your bash setup script to setup slic.

2) Somehow, when I say install iside  DIR/slic, it installs  inside DIR/slic/slic/bin, i.e. it adds extra "slic" 

best, Sergei

**Comment by JeremyMcCormick** [comment]
This duplicates #16.
