### ISSUE TITLE
Problem with the crossing angle

### ISSUE THREAD

**Issue by chekanov** [slaclab/slic#29]
This version of slic from Apr 20 works. But it fails with the crossing angle file. This example fails
(Geant cannot find B+ particle list):

 slic -P  particle.tbl -x -i output/pgun_pi10gev_001_truth.slcio  -g  ./sifcch7/sifcch7.lcdd -r 3 -m ./sifcch7/config/defaultILCCrossingAngle.mac -o output/pgun_pi10gev_001.slcio

So, it fails when I add the crossing angle, i.e. the file "defaultILCCrossingAngle.mac" with:

/run/initialize
/generator/setLorentzTransformationAngle 7 mrad
/run/beamOn 1

Otherwise, it works.

**Comment by JeremyMcCormick** [comment]
Okay let's just use existing #16 for this as it seems to be the same problem.  I'll try to take a look at this soon.
