### ISSUE TITLE
Macro error when running SLIC (???)

### ISSUE THREAD

**Issue by chekanov** [slaclab/slic#38]
Hello, Jeremy

 Thanks. I can run compile and run slic (master) using older LCIO package. I'm not only sure what these lines mean:
``
/control/execute ./sifcch7/config/defaultILCCrossingAngle.mac
/run/beamOn 3
``
(my mac file has only a value of angle). Why beamOn 3? I requested 3 events as input.

My output LCSIM runs, but produces an empty file. I use the latest LCSIM version 3.9

best, Sergei

**Comment by JeremyMcCormick** [comment]
Typically, you would use the command line switch to specify the number of events, so probably that can be removed.  There is a class in SLIC which puts all the command line arguments in the right order and executes them.

**Comment by JeremyMcCormick** [comment]
> My output LCSIM runs, but produces an empty file. I use the latest LCSIM version 3.9

Can you say more about this?  What steering file are you using?

I found that the LCIO v02-07 versions work okay with the LCIO binding in lcsim.  Which LCIO version did you specify in your SLIC build?

**Comment by JeremyMcCormick** [comment]
Hi, Sergei.

Can you say what SLIC command line you are running?  And also please inline the entire output from your job log.

I suspect you just need to run like this:

```
slic -g geom.lcdd -m defaultILCCrossingAngle.mac -r 3
```

...where the mac only sets the crossing angle.

What you put there for the macro commands doesn't make a lot of sense.  Where are you seeing this?

**Comment by JeremyMcCormick** [comment]
Also, for lcsim compatibility try LCIO v02-07-04 or v02-07-02.  I tested these and they seem to work fine.  I'm honestly not sure about v02-06 anymore (though it may also work).

**Comment by JeremyMcCormick** [comment]
This is the build recipe that I know works right now:

```
git clone https://github.com/slaclab/slic.git
cd slic; mkdir build; cd build
cmake -DLCIO_TAG=v02-07-04 -DINSTALL_DEPENDENCIES=ON -DGEANT4_INSTALL_DATA=ON -DCMAKE_INSTALL_PREFIX=../install ..
make # installs all deps
cmake .. # resolves all installed deps
make install # builds and installs slic
```

I think maybe specifying an "external" LCIO you already have installed is broken, but I believe I can fix this up fairly easily (need to add to `CMAKE_MODULE_PATH` so LCIO is able to find some CMake macros it needs for its package config files).

**Comment by JeremyMcCormick** [comment]
Getting back to your original issue, can you confirm that something like this works?

```
slic -g geom.lcdd -m defaultILCCrossingAngle.mac -r 3
```

Assuming you currently have a working installation...
