### ISSUE TITLE
MCParticleManager Mystery

### ISSUE THREAD

**Issue by whit2333** [slaclab/slic#42]
Hello,

I have a few questions about primary particle generation:

1. Can someone explain the logic in the recursive PrimaryGenerator?
https://github.com/slaclab/slic/blob/master/include/MCParticleManager.hh#L161

2. What are the assumptions on and relation between the collection of input MCParticles?

3. What are the various meanings of MCParticle::getGeneratorStatus() values?

4. To what extent can most of this be done outside of slic since we need to only know what particles are thrown?

Thanks in advance!

**Comment by JeremyMcCormick** [comment]
Closing this but I'll email you with some answers to these questions.
