### ISSUE TITLE
cannot be compiled using centos7

### ISSUE THREAD

**Issue by chekanov** [slaclab/slic#49]
Hi, 

slic cannot be compiled on Centos7 due to errors related to src/PluginLoader.cc. Compiler cannot find
dlsym, dlopen, etc

I suggest to add 
```
set (CMAKE_CXX_LINK_EXECUTABLE "${CMAKE_CXX_LINK_EXECUTABLE} -ldl")
```
to CMakeLists.txt. This fixes the problem on Centos7

**Comment by dreyling** [comment]
Thank @chekanov and yes, this would be nice!

This also solved the same linking problem on a Scientific Linux release 6.9 (Carbon) machine.

**Comment by mholtrop** [comment]
Added to CMakeLists.txt
The iss49 branch compiles on CENTOS7 and MacOS

**Comment by mholtrop** [comment]
Fixed and merged.
