### ISSUE TITLE
Move event print outs to plugin

### ISSUE THREAD

**Issue by JeremyMcCormick** [slaclab/slic#91]
Move hardcoded event print outs to an optional plugin.

**Comment by omar-moreno** [comment]
The more I think about this, the more I realize that these print outs don't belong in a plugin.  Instead, a logger should be added and these print outs should be part of the DEBUG stream.  One possibility is to just use boost logger but I'll look up other issues. 

For now, I'm going to comment the print outs and add them back in later as debug.

**Comment by omar-moreno** [comment]
This is partially solved by #94.
